import type { AlgCase } from './types'

// The 57 OLL cases with widely used standard algorithms (speedsolving wiki
// mains). Validated by tests: each alg must touch only last-layer stickers
// and every case pattern must be unique.
export const OLL_CASES: AlgCase[] = [
  { id: 'OLL 1', name: 'Runway', group: 'Dot', alg: "R U2 R2 F R F' U2 R' F R F'" },
  { id: 'OLL 2', name: 'Zamboni', group: 'Dot', alg: "F R U R' U' F' f R U R' U' f'" },
  { id: 'OLL 3', name: 'Anti-Nazi', group: 'Dot', alg: "f R U R' U' f' U' F R U R' U' F'" },
  { id: 'OLL 4', name: 'Nazi', group: 'Dot', alg: "f R U R' U' f' U F R U R' U' F'" },
  { id: 'OLL 17', name: 'Slash', group: 'Dot', alg: "R U R' U R' F R F' U2 R' F R F'" },
  { id: 'OLL 18', name: 'Crown', group: 'Dot', alg: "r U R' U R U2 r2 U' R U' R' U2 r" },
  { id: 'OLL 19', name: 'Bunny', group: 'Dot', alg: "M U R U R' U' M' R' F R F'" },
  { id: 'OLL 20', name: 'Checkers', group: 'Dot', alg: "r U R' U' M2 U R U' R' U' M'" },
  { id: 'OLL 5', name: 'Lefty Square', group: 'Square', alg: "r' U2 R U R' U r" },
  { id: 'OLL 6', name: 'Righty Square', group: 'Square', alg: "r U2 R' U' R U' r'" },
  { id: 'OLL 7', name: 'Lightning', group: 'Small lightning bolt', alg: "r U R' U R U2 r'" },
  { id: 'OLL 8', name: 'Reverse Lightning', group: 'Small lightning bolt', alg: "r' U' R U' R' U2 r" },
  { id: 'OLL 11', name: 'Downstairs', group: 'Small lightning bolt', alg: "r U R' U R' F R F' R U2 r'" },
  { id: 'OLL 12', name: 'Upstairs', group: 'Small lightning bolt', alg: "F R U R' U' F' U F R U R' U' F'" },
  { id: 'OLL 9', name: 'Kite', group: 'Fish', alg: "R U R' U' R' F R2 U R' U' F'" },
  { id: 'OLL 10', name: 'Anti-Kite', group: 'Fish', alg: "R U R' U R' F R F' R U2 R'" },
  { id: 'OLL 35', name: 'Fish Salad', group: 'Fish', alg: "R U2 R2 F R F' R U2 R'" },
  { id: 'OLL 37', name: 'Mounted Fish', group: 'Fish', alg: "F R' F' R U R U' R'" },
  { id: 'OLL 13', name: 'Gun', group: 'Knight move', alg: "F U R U' R2 F' R U R U' R'" },
  { id: 'OLL 14', name: 'Anti-Gun', group: 'Knight move', alg: "R' F R U R' F' R F U' F'" },
  { id: 'OLL 15', name: 'Squeegee', group: 'Knight move', alg: "r' U' r R' U' R U r' U r" },
  { id: 'OLL 16', name: 'Anti-Squeegee', group: 'Knight move', alg: "r U r' R U R' U' r U' r'" },
  { id: 'OLL 21', name: 'Double Headlights (H)', group: 'Cross', alg: "R U2 R' U' R U R' U' R U' R'" },
  { id: 'OLL 22', name: 'Pi', group: 'Cross', alg: "R U2 R2 U' R2 U' R2 U2 R" },
  { id: 'OLL 23', name: 'Headlights (U)', group: 'Cross', alg: "R2 D' R U2 R' D R U2 R" },
  { id: 'OLL 24', name: 'Chameleon (T)', group: 'Cross', alg: "r U R' U' r' F R F'" },
  { id: 'OLL 25', name: 'Bowtie (L)', group: 'Cross', alg: "F' r U R' U' r' F R" },
  { id: 'OLL 26', name: 'Antisune', group: 'Cross', alg: "R U2 R' U' R U' R'" },
  { id: 'OLL 27', name: 'Sune', group: 'Cross', alg: "R U R' U R U2 R'" },
  { id: 'OLL 28', name: 'Stealth', group: 'Corners oriented', alg: "r U R' U' M U R U' R'" },
  { id: 'OLL 57', name: 'Mummy', group: 'Corners oriented', alg: "R U R' U' M' U R U' r'" },
  { id: 'OLL 29', name: 'Spotted Chameleon', group: 'Awkward', alg: "R U R' U' R U' R' F' U' F R U R'" },
  { id: 'OLL 30', name: 'Anti-Spotted Chameleon', group: 'Awkward', alg: "F R' F R2 U' R' U' R U R' F2" },
  { id: 'OLL 41', name: 'Awkward Fish', group: 'Awkward', alg: "R U R' U R U2 R' F R U R' U' F'" },
  { id: 'OLL 42', name: 'Anti-Awkward Fish', group: 'Awkward', alg: "R' U' R U' R' U2 R F R U R' U' F'" },
  { id: 'OLL 31', name: 'Couch', group: 'P shape', alg: "R' U' F U R U' R' F' R" },
  { id: 'OLL 32', name: 'Anti-Couch', group: 'P shape', alg: "L U F' U' L' U L F L'" },
  { id: 'OLL 43', name: 'Anti-P', group: 'P shape', alg: "F' U' L' U L F" },
  { id: 'OLL 44', name: 'P', group: 'P shape', alg: "F U R U' R' F'" },
  { id: 'OLL 33', name: 'Key', group: 'T shape', alg: "R U R' U' R' F R F'" },
  { id: 'OLL 45', name: 'Suit Up (T)', group: 'T shape', alg: "F R U R' U' F'" },
  { id: 'OLL 34', name: 'City', group: 'C shape', alg: "R U R2 U' R' F R U R U' F'" },
  { id: 'OLL 46', name: 'Seein’ Headlights', group: 'C shape', alg: "R' U' R' F R F' U R" },
  { id: 'OLL 36', name: 'Wario', group: 'W shape', alg: "L' U' L U' L' U L U L F' L' F" },
  { id: 'OLL 38', name: 'Mario', group: 'W shape', alg: "R U R' U R U' R' U' R' F R F'" },
  { id: 'OLL 39', name: 'Big Lightning', group: 'Big lightning bolt', alg: "L F' L' U' L U F U' L'" },
  { id: 'OLL 40', name: 'Anti-Big Lightning', group: 'Big lightning bolt', alg: "R' F R U R' U' F' U R" },
  { id: 'OLL 47', name: 'Anti-Breakneck', group: 'Small L', alg: "R' U' R' F R F' R' F R F' U R" },
  { id: 'OLL 48', name: 'Breakneck', group: 'Small L', alg: "F R U R' U' R U R' U' F'" },
  { id: 'OLL 49', name: 'Right Back Squeezy', group: 'Small L', alg: "r U' r2 U r2 U r2 U' r" },
  { id: 'OLL 50', name: 'Right Front Squeezy', group: 'Small L', alg: "r' U r2 U' r2 U' r2 U r'" },
  { id: 'OLL 53', name: 'Frying Pan', group: 'Small L', alg: "r' U' R U' R' U R U' R' U2 r" },
  { id: 'OLL 54', name: 'Anti-Frying Pan', group: 'Small L', alg: "r U R' U R U' R' U R U2 r'" },
  { id: 'OLL 51', name: 'Bottlecap', group: 'I shape', alg: "F U R U' R' U R U' R' F'" },
  { id: 'OLL 52', name: 'Rice Cooker', group: 'I shape', alg: "R U R' U R U' B U' B' R'" },
  { id: 'OLL 55', name: 'Highway', group: 'I shape', alg: "R' F R U R U' R2 F' R2 U' R' U R U R'" },
  { id: 'OLL 56', name: 'Streetlights', group: 'I shape', alg: "r' U' r U' R' U R U' R' U R r' U r" },
]
